# Generated by Django 4.2 on 2024-02-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("default", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_profile"),
        ),
    ]
