# Generated by Django 4.2 on 2024-02-18 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("default", "0004_delete_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("doctor", models.CharField(max_length=100, null=True)),
                ("patient", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
