# Generated by Django 4.2 on 2024-02-18 08:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="description",
        ),
    ]
