# Generated by Django 4.2 on 2024-02-18 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_appointments_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointments",
        ),
    ]
