# Generated by Django 4.2 on 2024-02-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Appointments",
        ),
    ]
