# Generated by Django 4.2 on 2024-02-18 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_appointment_delete_appointments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
