# Generated by Django 4.2 on 2024-02-18 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
