# Generated by Django 4.2 on 2024-02-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
