# Generated by Django 4.2 on 2024-02-18 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_remove_appointment_doctor_appointment_patient"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
