# Generated by Django 4.2 on 2024-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="patient",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
